Repository TeamWazard/wazard-server, pull requests merged in 2023-06, with the labels that each got.

#202 [Test/#200] 특정 근무자 상세 조회 repository 단위 테스트 & 구현
  common-component/src/main/java/shop/wazard/util/exception/StatusEnum.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/AbsentRecordJpaForWorkerManagementRepository.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/EnterRecordJpaForWorkerManagementRepository.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/ExitRecordJpaForWorkerManagementRepository.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapter.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerManagementMapper.java
  worker-management-component/src/main/java/shop/wazard/application/WorkerManagementServiceImpl.java
  worker-management-component/src/main/java/shop/wazard/application/port/in/WorkerManagementService.java
  worker-management-component/src/main/java/shop/wazard/application/port/out/CommuteRecordForWorkerManagementPort.java
  worker-management-component/src/main/java/shop/wazard/dto/GetWorkerAttendanceRecordReqDto.java
  worker-management-component/src/test/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapterTest.java
  worker-management-component/src/test/java/shop/wazard/application/WorkerManagementServiceTest.java
Labels: feature, fix, test, 심종한, size/XL

#193 [Feat/#192] 대타기록조회 repository 테스트코드 및 구현
  entity-component/src/main/java/shop/wazard/entity/worker/ReplaceWorkerJpa.java
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/ReplaceJpaForWorkerRepository.java
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerDbAdapter.java
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerMapper.java
  worker-component/src/test/java/shop/wazard/adapter/out/persistence/WorkerDbAdapterTest.java
Labels: feature, test, 진윤규, size/L

#205 [Feat/#198] 근무자 나의 태도 점수 조회 service 테스트 코드 및 개발 코드 구현
  common-component/src/main/java/shop/wazard/util/calculator/Calculator.java
  mypage-component/src/main/java/shop/wazard/adapter/out/persistence/MyPageDbAdapter.java
  mypage-component/src/main/java/shop/wazard/application/MyPageServiceImpl.java
  mypage-component/src/main/java/shop/wazard/application/port/in/MyPageService.java
  mypage-component/src/main/java/shop/wazard/application/port/out/WorkRecordForMyPagePort.java
  mypage-component/src/main/java/shop/wazard/dto/GetMyAttitudeScoreReqDto.java
  mypage-component/src/main/java/shop/wazard/dto/GetMyAttitudeScoreResDto.java
  mypage-component/src/test/java/shop/wazard/application/MyPageServiceImplTest.java
Labels: feature, test, 김민규, size/L

#195 [Feat/#194] 본인대타기록 조회 controller 구현
  entity-component/src/main/java/shop/wazard/entity/worker/ReplaceWorkerJpa.java
  worker-component/src/main/java/shop/wazard/adapter/in/rest/WorkerController.java
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/AccountJpaForWorkerRepository.java
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/ReplaceJpaForWorkerRepository.java
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerDbAdapter.java
  worker-component/src/main/java/shop/wazard/application/WorkerServiceImpl.java
  worker-component/src/test/java/shop/wazard/adapter/out/persistence/WorkerDbAdapterTest.java
Labels: feature, 진윤규, size/S

#211 [Fix/#208] 메일 인증 request validation 추가
  smtp-component/src/main/java/shop/wazard/adapter/in/rest/EmailController.java
  smtp-component/src/main/java/shop/wazard/application/EmailServiceImpl.java
  smtp-component/src/main/java/shop/wazard/application/port/in/EmailService.java
  smtp-component/src/main/java/shop/wazard/dto/EmailAuthReqDto.java
  smtp-component/src/main/java/shop/wazard/dto/EmailAuthResDto.java
  smtp-component/src/main/java/shop/wazard/exception/FailCreateEmailForm.java
  smtp-component/src/main/java/shop/wazard/exception/FailSendEmail.java
  smtp-component/src/main/resources/templates/certificationMailForm.html
Labels: bug, fix, 심종한, size/M

#197 [Feat/#196] 전체대타기록 조회 service테스트코드 및 구현
  worker-component/src/main/java/shop/wazard/application/port/out/WorkerPort.java
  worker-component/src/main/java/shop/wazard/dto/GetMyReplaceReqDto.java
  worker-component/src/main/java/shop/wazard/dto/GetMyReplaceResDto.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapter.java
  worker-management-component/src/main/java/shop/wazard/application/WorkerManagementServiceImpl.java
  worker-management-component/src/main/java/shop/wazard/application/port/in/WorkerManagementService.java
  worker-management-component/src/main/java/shop/wazard/application/port/out/ReplaceForWorkerManagementPort.java
  worker-management-component/src/main/java/shop/wazard/dto/GetAllReplaceRecordReqDto.java
  worker-management-component/src/main/java/shop/wazard/dto/GetAllReplaceRecordResDto.java
  worker-management-component/src/test/java/shop/wazard/application/WorkerManagementServiceTest.java
Labels: feature, test, 진윤규, size/L

#218 [Fix/#215] 초대 대기자 목록 조회 uri 변경
  worker-management-component/src/main/java/shop/wazard/adapter/in/rest/WorkerManagementController.java
  worker-management-component/src/main/java/shop/wazard/application/WorkerManagementServiceImpl.java
  worker-management-component/src/main/java/shop/wazard/application/port/in/WorkerManagementService.java
  worker-management-component/src/main/java/shop/wazard/dto/WaitingWorkerReqDto.java
  worker-management-component/src/test/java/shop/wazard/application/WorkerManagementServiceTest.java
Labels: fix, 심종한, size/S

#212 [Feat/#210] 근무자 나의 태도 점수 조회 repository 테스트 코드 및 개발 코드 구현
  mypage-component/src/main/java/shop/wazard/adapter/out/persistence/CompanyJpaForMyPageRepository.java
  mypage-component/src/main/java/shop/wazard/adapter/out/persistence/MyPageDbAdapter.java
  mypage-component/src/test/java/shop/wazard/adapter/out/persistence/MyPageDbAdapterTest.java
Labels: feature, test, 김민규, size/L

#216 [Fix/#213] 고용주 요일별 출근부 조회 uri 수정
  attendance-component/src/main/java/shop/wazard/adapter/in/rest/AttendanceController.java
  attendance-component/src/main/java/shop/wazard/application/AttendanceServiceImpl.java
  attendance-component/src/main/java/shop/wazard/application/domain/Attendance.java
  attendance-component/src/main/java/shop/wazard/application/port/in/AttendanceService.java
  attendance-component/src/main/java/shop/wazard/dto/GetAttendanceByDayOfTheWeekReqDto.java
  attendance-component/src/test/java/shop/wazard/application/AttendanceServiceImplTest.java
Labels: fix, 김민규, size/M

#223 [Feat/#222] 근무자 나의 태도 점수 조회 controller 개발 코드 구현
  mypage-component/src/main/java/shop/wazard/adapter/in/rest/MyPageController.java
Labels: feature, 김민규, size/S

#225 [Feat/#221] 특정 근무자 상세조회 controller 구현 & 예외 핸들러 추가
  worker-management-component/src/main/java/shop/wazard/adapter/in/rest/WorkerManagementController.java
  worker-management-component/src/main/java/shop/wazard/application/WorkerManagementServiceImpl.java
  worker-management-component/src/main/java/shop/wazard/exception/UnsupportedDateException.java
  worker-management-component/src/main/java/shop/wazard/exception/WorkerManagementExceptionHandler.java
  worker-management-component/src/test/java/shop/wazard/application/WorkerManagementServiceTest.java
Labels: feature, 심종한, size/M

#229 [Feat/#228] dev 브랜치 CI 적용
  .github/workflows/gradleTest.yml
Labels: feature, 김민규, size/XS

#232 [Feat/#230] 고용주 근무자 태도 점수 조회 service 테스트 코드 및 개발 코드 구현
  worker-management-component/src/main/java/shop/wazard/application/WorkerManagementServiceImpl.java
  worker-management-component/src/main/java/shop/wazard/application/domain/WorkRecordForWorkerManagement.java
  worker-management-component/src/main/java/shop/wazard/application/port/in/WorkerManagementService.java
  worker-management-component/src/main/java/shop/wazard/application/port/out/WorkRecordForWorkerManagementPort.java
  worker-management-component/src/main/java/shop/wazard/dto/GetWorkerAttitudeScoreReqDto.java
  worker-management-component/src/main/java/shop/wazard/dto/GetWorkerAttitudeScoreResDto.java
  worker-management-component/src/test/java/shop/wazard/application/WorkerManagementServiceTest.java
Labels: feature, test, 김민규, size/L

#235 [Feat/#234] 고용주 근무자 태도 점수 조회 repository 테스트 코드 및 개발 코드 구현
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/AbsentRecordJpaForWorkerManagementRepository.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/CompanyJpaForWorkerManagementRepository.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/EnterRecordJpaForWorkerManagementRepository.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapter.java
  worker-management-component/src/main/java/shop/wazard/application/WorkerManagementServiceImpl.java
  worker-management-component/src/main/java/shop/wazard/application/port/out/WorkRecordForWorkerManagementPort.java
  worker-management-component/src/test/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapterTest.java
  worker-management-component/src/test/java/shop/wazard/application/WorkerManagementServiceTest.java
Labels: feature, test, 김민규, size/L

#237 [Fix/#236] 고용주 근무자 태도 점수 조회 dto에서 companyId 제거 및 람다식 변수명 변경
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapter.java
  worker-management-component/src/main/java/shop/wazard/dto/GetWorkerAttitudeScoreReqDto.java
  worker-management-component/src/test/java/shop/wazard/application/WorkerManagementServiceTest.java
Labels: fix, 김민규, size/XS

#241 [Fix/#240] 업장 등록 요구사항 변경
  attendance-component/src/test/java/shop/wazard/adapter/out/persistence/AttendanceDbAdapterTest.java
  company-component/src/main/java/shop/wazard/adapter/out/persistence/CompanyMapper.java
  company-component/src/main/java/shop/wazard/application/domain/Company.java
  company-component/src/main/java/shop/wazard/application/domain/CompanyInfo.java
  company-component/src/main/java/shop/wazard/dto/RegisterCompanyReqDto.java
  company-component/src/test/java/shop/wazard/adapter/out/persistence/CompanyDbAdapterTest.java
  company-component/src/test/java/shop/wazard/application/CompanyServiceTest.java
  entity-component/src/main/java/shop/wazard/entity/company/CompanyJpa.java
  mypage-component/src/test/java/shop/wazard/adapter/out/persistence/MyPageDbAdapterTest.java
  worker-component/src/test/java/shop/wazard/adapter/out/persistence/WorkerDbAdapterTest.java
  worker-management-component/src/test/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapterTest.java
Labels: fix, 심종한, size/L

#244 [Feat/#242] 근무자 초대 메일 전송 service 구현
  smtp-component/src/main/java/shop/wazard/application/EmailServiceImpl.java
  smtp-component/src/main/java/shop/wazard/application/port/in/EmailService.java
  smtp-component/src/main/java/shop/wazard/dto/InviteWorkerReqDto.java
  smtp-component/src/main/resources/templates/inviteMailForm.html
Labels: feature, 심종한, size/L

#245 [Feat/#243] 근무자 초대 메일 전송 controller 구현
  smtp-component/src/main/java/shop/wazard/adapter/in/rest/EmailController.java
  smtp-component/src/main/java/shop/wazard/application/EmailServiceImpl.java
  smtp-component/src/main/java/shop/wazard/dto/InviteWorkerResDto.java
  smtp-component/src/main/resources/templates/invitationMailForm.html
Labels: feature, 심종한, size/M

#247 [Fix/#246] 근무자 내 평균 태도 점수 조회 request dto 불필요 필드 삭제
  mypage-component/src/main/java/shop/wazard/dto/GetMyAttitudeScoreReqDto.java
  mypage-component/src/test/java/shop/wazard/application/MyPageServiceImplTest.java
Labels: fix, 김민규, size/XS

#254 [Feat] 전체대타기록 조회 repository & controller 구현
  worker-management-component/src/main/java/shop/wazard/adapter/in/rest/WorkerManagementController.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/ReplaceJpaForWorkerManagementRepository.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapter.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerManagementMapper.java
  worker-management-component/src/test/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapterTest.java
Labels: feature, test, 진윤규, size/L

#257 [Feat/#253] 전체 대타기록 조회 repository & controller 구현
  worker-management-component/src/main/java/shop/wazard/adapter/in/rest/WorkerManagementController.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/ReplaceJpaForWorkerManagementRepository.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapter.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerManagementMapper.java
  worker-management-component/src/test/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapterTest.java
Labels: feature, fix, 김민규, 진윤규, size/L

#251 [Feat/#250] 계약정보 Entity 개발 초안
  entity-component/src/main/java/shop/wazard/entity/contract/ContractJpa.java
Labels: feature, 김민규, size/M, attention❗️

#260 [Feat/#258] 초기 계약정보 등록 service 구현 & 단위 테스트
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapter.java
  worker-management-component/src/main/java/shop/wazard/application/WorkerManagementServiceImpl.java
  worker-management-component/src/main/java/shop/wazard/application/port/in/WorkerManagementService.java
  worker-management-component/src/main/java/shop/wazard/application/port/out/ContractForWorkerManagementPort.java
  worker-management-component/src/main/java/shop/wazard/application/port/out/WaitingListForWorkerManagementPort.java
  worker-management-component/src/main/java/shop/wazard/dto/RegisterContractInfoReqDto.java
  worker-management-component/src/main/java/shop/wazard/dto/RegisterContractInfoResDto.java
  worker-management-component/src/test/java/shop/wazard/application/WorkerManagementServiceTest.java
Labels: feature, test, 심종한, size/L

#261 [Feat/#259] 초기 계약정보 등록 repository 구현 & 단위 테스트
  entity-component/src/main/java/shop/wazard/entity/contract/ContractJpa.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/ContractForWorkerManagementRepository.java
  worker-management-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapter.java
  worker-management-component/src/test/java/shop/wazard/adapter/out/persistence/WorkerManagementDbAdapterTest.java
Labels: feature, test, 심종한, size/L

#263 [Feat/#262] 초기 계약 정보 등록 controller 구현
  worker-management-component/src/main/java/shop/wazard/adapter/in/rest/WorkerManagementController.java
  worker-management-component/src/main/java/shop/wazard/dto/RegisterContractInfoReqDto.java
Labels: feature, 심종한, size/S

#265 [Feat/#264] 초기 계약정보 조회 service 구현 & 단위 테스트
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerDbAdapter.java
  worker-component/src/main/java/shop/wazard/application/WorkerServiceImpl.java
  worker-component/src/main/java/shop/wazard/application/port/in/WorkerService.java
  worker-component/src/main/java/shop/wazard/application/port/out/ContractForWorkerPort.java
  worker-component/src/main/java/shop/wazard/dto/GetEarlyContractInfoReqDto.java
  worker-component/src/main/java/shop/wazard/dto/GetEarlyContractInfoResDto.java
  worker-component/src/test/java/shop/wazard/application/WorkerServiceImplTest.java
Labels: feature, test, 진윤규, size/L

#277 [Feat/#267] 초기 계약정보 조회 repository 구현 & 단위 테스트
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/ContractJpaForWorkerRepository.java
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerDbAdapter.java
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerMapper.java
  worker-component/src/test/java/shop/wazard/adapter/out/persistence/WorkerDbAdapterTest.java
Labels: feature, test, 진윤규, size/L

#268 [Feat/#266] 계약정보 동의/비동의 service 단위 테스트 및 코드 구현
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerDbAdapter.java
  worker-component/src/main/java/shop/wazard/application/WorkerServiceImpl.java
  worker-component/src/main/java/shop/wazard/application/domain/ContractInfo.java
  worker-component/src/main/java/shop/wazard/application/port/in/WorkerService.java
  worker-component/src/main/java/shop/wazard/application/port/out/ContractForWorkerPort.java
  worker-component/src/main/java/shop/wazard/dto/CheckAgreementReqDto.java
  worker-component/src/main/java/shop/wazard/dto/CheckAgreementResDto.java
  worker-component/src/test/java/shop/wazard/application/WorkerServiceImplTest.java
Labels: feature, test, 김민규, size/M

#272 [Feat/#271] 초기 계약 정보 동의/비동의 controller 개발 코드 구현
  worker-component/src/main/java/shop/wazard/adapter/in/rest/WorkerController.java
Labels: feature, 김민규, size/XS

#276 [Fix/#275] 초기 계약정보 동의/비동의 대기자 목록 변경
  common-component/src/main/java/shop/wazard/util/exception/StatusEnum.java
  entity-component/src/main/java/shop/wazard/entity/contract/ContractJpa.java
  worker-component/src/main/java/shop/wazard/adapter/in/rest/WorkerController.java
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/ContractInfoForWorkerMapper.java
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/WaitingListForWorkerMapper.java
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/WaitingListJpaForWorkerRepository.java
  worker-component/src/main/java/shop/wazard/adapter/out/persistence/WorkerDbAdapter.java
  worker-component/src/main/java/shop/wazard/application/WorkerServiceImpl.java
  worker-component/src/main/java/shop/wazard/application/domain/ContractInfo.java
  worker-component/src/main/java/shop/wazard/application/port/in/WorkerService.java
  worker-component/src/main/java/shop/wazard/application/port/out/ContractForWorkerPort.java
  worker-component/src/main/java/shop/wazard/application/port/out/WaitingListForWorkerPort.java
  worker-component/src/main/java/shop/wazard/dto/CheckAgreementResDto.java
  worker-component/src/main/java/shop/wazard/dto/PatchContractAgreementReqDto.java
  worker-component/src/main/java/shop/wazard/dto/PatchContractAgreementResDto.java
  worker-component/src/main/java/shop/wazard/exception/WaitingListNotFoundException.java
  worker-component/src/main/java/shop/wazard/exception/WorkerExceptionHandler.java
  worker-component/src/test/java/shop/wazard/adapter/out/persistence/WorkerDbAdapterTest.java
  worker-component/src/test/java/shop/wazard/application/WorkerServiceImplTest.java
Labels: fix, 김민규, size/L

#274 [Fix/#273] 초기 계약 정보 동의/비동의 전반적인 변수명 변경
  worker-component/src/main/java/shop/wazard/adapter/in/rest/WorkerController.java
  worker-component/src/main/java/shop/wazard/application/WorkerServiceImpl.java
  worker-component/src/main/java/shop/wazard/application/domain/ContractInfo.java
  worker-component/src/main/java/shop/wazard/application/port/in/WorkerService.java
  worker-component/src/main/java/shop/wazard/dto/ModifyContractAgreementReqDto.java
  worker-component/src/main/java/shop/wazard/dto/ModifyContractAgreementResDto.java
  worker-component/src/test/java/shop/wazard/application/WorkerServiceImplTest.java
Labels: fix, 김민규, size/M
