Repository TeamWazard/wazard-server, pull requests merged in 2023-04, with the labels that each got.

#12 [Test/#8] 고용주 회원정보 수정 통합 테스트
  account-component/src/main/java/shop/wazard/dto/UpdateCompanyAccountInfoReqDto.java
  account-component/src/main/java/shop/wazard/dto/UpdateCompanyAccountInfoResDto.java
  account-component/src/test/java/shop/wazard/adapter/in/rest/CompanyAccountControllerTest.java
  account-component/src/test/java/shop/wazard/application/port/in/CompanyAccountServiceTest.java
Labels: test, 심종한, size/L

#15 [Fix/#13] dto-req, entity-domain 클래스 통합
  account-component/src/main/java/shop/wazard/adapter/in/rest/CommonAccountController.java
  account-component/src/main/java/shop/wazard/adapter/in/rest/CompanyAccountController.java
  account-component/src/main/java/shop/wazard/adapter/in/rest/ControllerConverter.java
  account-component/src/main/java/shop/wazard/adapter/in/rest/MemberAccountController.java
  account-component/src/main/java/shop/wazard/adapter/in/rest/request/JoinReq.java
  account-component/src/main/java/shop/wazard/adapter/in/rest/request/LoginReq.java
  account-component/src/main/java/shop/wazard/adapter/in/rest/response/JoinRes.java
  account-component/src/main/java/shop/wazard/adapter/in/rest/response/LoginRes.java
  account-component/src/main/java/shop/wazard/adapter/out/persistence/Account.java
  account-component/src/main/java/shop/wazard/adapter/out/persistence/AccountDbAdapter.java
  account-component/src/main/java/shop/wazard/adapter/out/persistence/AccountDomainConverter.java
  account-component/src/main/java/shop/wazard/adapter/out/persistence/AccountJpaRepository.java
  account-component/src/main/java/shop/wazard/application/port/UserDetailServiceImpl.java
  account-component/src/main/java/shop/wazard/application/port/out/LoadAccountPort.java
  account-component/src/main/java/shop/wazard/domain/AccountDomain.java
  account-component/src/main/java/shop/wazard/domain/AccountStatusDomain.java
  account-component/src/main/java/shop/wazard/domain/GenderTypeDomain.java
  account-component/src/main/java/shop/wazard/domain/README.md
  account-component/src/main/java/shop/wazard/dto/JoinReqDto.java
  account-component/src/main/java/shop/wazard/dto/LoginReqDto.java
  common-component/src/main/java/shop/wazard/util/response/Message.java
Labels: fix, 심종한, size/L

#6 [Feat/#5] 메일 인증번호 전송 기능
  build.gradle
  common-component/src/main/java/shop/wazard/util/response/StatusEnum.java
  common-component/src/main/java/shop/wazard/util/security/WebSecurityConfig.java
  settings.gradle
  smtp-component/build.gradle
  smtp-component/out/production/resources/templates/mailForm.html
  smtp-component/src/main/java/shop/wazard/adapter/in/rest/EmailController.java
  smtp-component/src/main/java/shop/wazard/adapter/in/rest/request/EmailAuthReq.java
  smtp-component/src/main/java/shop/wazard/adapter/in/rest/response/EmailAuthRes.java
  smtp-component/src/main/java/shop/wazard/application/port/EmailServiceImpl.java
  smtp-component/src/main/java/shop/wazard/application/port/in/EmailService.java
  smtp-component/src/main/java/shop/wazard/exception/EmailExceptionHandler.java
  smtp-component/src/main/java/shop/wazard/exception/FailCreateEmailForm.java
  smtp-component/src/main/java/shop/wazard/exception/FailSendEmail.java
  smtp-component/src/main/resources/templates/mailForm.html
Labels: feature, 심종한, size/L

#17 [Fix/#16] 고용주 회원 정보 수정 단위 테스트 코드 수정
  account-component/src/test/java/shop/wazard/application/port/in/CompanyAccountServiceTest.java
Labels: fix, 김민규, size/S

#20 [Fix/#19] 고용주 회원정보 수정 service 단위 테스트 수정
  account-component/src/main/java/shop/wazard/adapter/out/persistence/Account.java
  account-component/src/main/java/shop/wazard/adapter/out/persistence/AccountStatus.java
  account-component/src/main/java/shop/wazard/adapter/out/persistence/GenderType.java
  account-component/src/main/java/shop/wazard/application/port/CompanyAccountServiceImpl.java
  account-component/src/main/java/shop/wazard/dto/UpdateCompanyAccountInfoReqDto.java
  account-component/src/test/java/shop/wazard/adapter/in/rest/CompanyAccountControllerTest.java
  account-component/src/test/java/shop/wazard/application/port/CompanyAccountServiceTest.java
  account-component/src/test/java/shop/wazard/application/port/in/CompanyAccountServiceTest.java
Labels: fix, 심종한, size/L

#24 [Feat/#18] 고용주 회원 정보 수정 api 추가
  account-component/src/main/java/shop/wazard/application/port/CompanyAccountServiceImpl.java
  account-component/src/main/java/shop/wazard/application/port/in/CompanyAccountService.java
Labels: feature, 김민규, size/S
